# A string used to distinguish different Supabase projects on the same host
project_id = "gdev-ai-chatbot"

[api]
# Port to use for the API URL.
port = 55321
schemas = ["public", "storage"]
# Extra schemas to add to the search_path of every request.
extra_search_path = ["public", "extensions"]
# The maximum number of rows returns from a view, table, or stored procedure. Limits payload size for accidental or malicious requests.
max_rows = 1000

[db]
# Port to use for the local database URL.
port = 55322
# The database major version to use. This has to be the same as your remote database's. Run `SHOW server_version;` on the remote database to check.
major_version = 15

[studio]
# Port to use for Supabase Studio.
port = 55323

# Email testing server. Emails sent with the local dev setup are not actually sent - rather, they are monitored, and you can view the emails that would have been sent from the dashboard.
[inbucket]
# Port to use for the email testing server.
port = 55324

[analytics]
# Port to use for the analytics server.
port = 55327

[storage]
# The maximum file size allowed (e.g. "5MB", "500KB").
file_size_limit = "50MB"

[auth]
# The base URL of your website. Used as an allow-list for redirects and for constructing URLs used in emails.
site_url = "http://localhost:3000"
# A list of *exact* URLs that auth providers are permitted to redirect to post authentication.
additional_redirect_urls = ["https://localhost:3000"]
# How long tokens are valid for, in seconds. Defaults to 3600 (1 hour), maximum 604,800 seconds (one week).
jwt_expiry = 3600
# Allow/disallow new user signups to your project.
enable_signup = true

[auth.email]
# Allow/disallow new user signups via email to your project.
enable_signup = true
# If enabled, users need to confirm their email address before signing in.
enable_confirmations = false
